### PR TITLE
Integrate UI with task list and score list

### LINKED ISSUE #79: Integrate UI with task list and score list

### PR DESCRIPTION
**Pull request by CarrieLi1015**
Integrated UI with task list and score list to display the respective student's information together with check.

Issue: the title text display for task list and score list is a bit off, will adjust it in the following UI increment.

close #79 

When no student is ever being checked
Screenshot 2023-03-13 at 11 57 36 PM

Student with task and score
Screenshot 2023-03-13 at 11 57 48 PM

Student with task but no score
Screenshot 2023-03-13 at 11 58 17 PM

### CODE REVIEW

**Review by QQH0828 — COMMENTED** [review]
LGTM! I noticed that the sentence of `no student being checked now` is not showing totally as `y` of `being` only shows half of it. But I think it should be fine. Thanks for doing the great work!

**Comment by CarrieLi1015** [comment]
> LGTM! I noticed that the sentence of `no student being checked now` is not showing totally as `y` of `being` only shows half of it. But I think it should be fine. Thanks for doing the great work!

Yup, I mentioned the problem on my comment. Will fix it during the next UI increment.

**Comment by QQH0828** [comment]
Oh, Sorry, I did see it. Thanks.

**Comment by CarrieLi1015** [comment]
> Oh, Sorry, I did see it. Thanks.

No problem!

**Review by toh-xinyi — COMMENTED** [review]
LGTM! Very nice :D

**Pull request merged**
